### ISSUE TITLE
application with flutter background view crash

### ISSUE THREAD

**Issue by Thetyne** [adee42/flutter_keyboard_visibility#11]
just for information.

if i include your plugin inside a android application who use background flutter view (background service), application crash.

Application crash because a background service call "GeneratedPluginRegistrant.registerWith" with all plugin and your code haven't protection in this case (line 32 in KeyboardVisibilityPlugin)

LOG:

java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.app.Activity.findViewById(int)' on a null object reference
        at com.github.adee42.keyboardvisibility.KeyboardVisibilityPlugin.<init>(KeyboardVisibilityPlugin.java:32)
        at com.github.adee42.keyboardvisibility.KeyboardVisibilityPlugin.registerWith(KeyboardVisibilityPlugin.java:93)
        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:40)
        at com.keyneosoft.keyapp.Application.registerWith(Application.java:19)

**Comment by adee42** [comment]
I changed the behavior in ver. 0.5.3. At least it should not crash, I am unsure if it works properly with every app

**Comment by rifkyputra** [comment]
in my case i got error when in ver ^0.5.6 (MissingPluginException No implementation found  for method getDatabasesPath on channel com.tekartik.sqflite)
i resolved the issue by downgrading to 0.5.3
