### ISSUE TITLE
 The application is broken

### ISSUE THREAD

**Issue by hahai96** [adee42/flutter_keyboard_visibility#16]
```
E/AndroidRuntime( 7962): java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.getWindowVisibleDisplayFrame(android.graphics.Rect)' on a null object reference
E/AndroidRuntime( 7962): 	at com.github.adee42.keyboardvisibility.KeyboardVisibilityPlugin.onGlobalLayout(KeyboardVisibilityPlugin.java:40)
E/AndroidRuntime( 7962): 	at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:945)
E/AndroidRuntime( 7962): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2290)
E/AndroidRuntime( 7962): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1432)
E/AndroidRuntime( 7962): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6861)
E/AndroidRuntime( 7962): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1026)
E/AndroidRuntime( 7962): 	at android.view.Choreographer.doCallbacks(Choreographer.java:838)
E/AndroidRuntime( 7962): 	at android.view.Choreographer.doFrame(Choreographer.java:769)
E/AndroidRuntime( 7962): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1012)
E/AndroidRuntime( 7962): 	at android.os.Handler.handleCallback(Handler.java:790)
E/AndroidRuntime( 7962): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 7962): 	at android.os.Looper.loop(Looper.java:171)
E/AndroidRuntime( 7962): 	at android.app.ActivityThread.main(ActivityThread.java:6651)
E/AndroidRuntime( 7962): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 7962): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
E/AndroidRuntime( 7962): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
```

I have 2 screens for oneScree and twoScreen. Twoscreen screen will listen to onkeyboard event, 
but when i click on textfield in onescreen app will be stopped.

**Comment by 330676687** [comment]
I have same question

**Comment by adee42** [comment]
I just published a new update, can you check this one?

**Comment by 330676687** [comment]
0.5.5 isn't solve

**Comment by adee42** [comment]
The new version should be 0.5.6. If that doesn't solve the problem, can you please provide an example?

**Comment by 330676687** [comment]
0.5.6 OK, Thanks
