### ISSUE TITLE
 The application is suddenly stopped

### ISSUE THREAD

**Issue by hahai96** [adee42/flutter_keyboard_visibility#18]
keyboard_visibility 0.5.6

My application was stopped when I just built it.

```
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.app.Application android.app.Activity.getApplication()' on a null object reference
E/AndroidRuntime(23064): 	at com.github.adee42.keyboardvisibility.KeyboardVisibilityPlugin.registerWith(KeyboardVisibilityPlugin.java:107)
E/AndroidRuntime(23064): 	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:39)
E/AndroidRuntime(23064): 	at com.famtech.xeminh.Application.registerWith(Application.java:26)
E/AndroidRuntime(23064): 	at com.famtech.xeminh.bgtracking.GeofencingService.startGeofencingService(GeofencingService.java:71)
E/AndroidRuntime(23064): 	at com.famtech.xeminh.bgtracking.GeofencingService.onCreate(GeofencingService.java:50)
E/AndroidRuntime(23064): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3378)
```

**Comment by sharad-paghadal** [comment]
@hahai96 
I'm facing same issue with using another package `workmanager`. Please let me know if you know the fix of this.
