### ISSUE TITLE
Broken after Interstitial Ad by admob

### ISSUE THREAD

**Issue by hsombini** [adee42/flutter_keyboard_visibility#31]
Testing this case scenario using version 0.5.6 not errors are thrown, works fine before Interstitial ad is executed

Version 0.5.5 crashes the app, also works fine before Interstitial ad is executed

```
E/AndroidRuntime( 6558): java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.getWindowVisibleDisplayFrame(android.graphics.Rect)' on a null object reference
E/AndroidRuntime( 6558): 	at com.github.adee42.keyboardvisibility.KeyboardVisibilityPlugin.onGlobalLayout(KeyboardVisibilityPlugin.java:40)
E/AndroidRuntime( 6558): 	at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:945)
E/AndroidRuntime( 6558): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2372)
E/AndroidRuntime( 6558): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1481)
E/AndroidRuntime( 6558): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7393)
E/AndroidRuntime( 6558): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
E/AndroidRuntime( 6558): 	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
E/AndroidRuntime( 6558): 	at android.view.Choreographer.doFrame(Choreographer.java:696)
E/AndroidRuntime( 6558): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
E/AndroidRuntime( 6558): 	at android.os.Handler.handleCallback(Handler.java:873)
E/AndroidRuntime( 6558): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 6558): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime( 6558): 	at android.app.ActivityThread.main(ActivityThread.java:6724)
E/AndroidRuntime( 6558): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 6558): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
E/AndroidRuntime( 6558): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
I/Process ( 6558): Sending signal. PID: 6558 SIG: 9
```

**Comment by alekseisubbotin** [comment]
In-app payments seem to break the plugin too.

**Comment by bilalbaz1** [comment]
Have you found a solution to this? Or an alternative method?

**Comment by Moonspeaker** [comment]
Does it still happen for this library's latest verison? I've seen the code, the author should have fixed it

**Comment by Moonspeaker** [comment]
Oops, I'm sorry, the code is still bad. Don't know whether it happens on IOS, but can fork and fix this on Android. Alternative method would be to make some hacks using mediaquery or dart:ui window singleton

**Comment by Moonspeaker** [comment]
I can fork and try to fix this on Android. Alternative method would be to make some hacks using mediaquery or dart:ui window singleton
