### ISSUE TITLE
My app is crashing because of this package

### ISSUE THREAD

**Issue by remoteportal** [adee42/flutter_keyboard_visibility#43]
I was told to report this to you:

"Flutter's new background execution feature (described here: https://medium.com/flutter-io/executing-dart-in-the-background-with-flutter-plugins-and-geofencing-2b3e40a1a124) allows plugins to be registered in a background context (e.g. a Service)."

I don't know what this keyboard visibility package does and checked several packages I'm using and can't figure out who is calling it or why, but it's crashing my app, probably because of the warning above.  Can you please update your package?

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.app.Application android.app.Activity.getApplication()' on a null object reference
       at com.github.adee42.keyboardvisibility.KeyboardVisibilityPlugin.registerWith(KeyboardVisibilityPlugin.java:107)
       at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:37)
       at com.onlyup.runsergeant.MainApplication.registerWith(MainApplication.java:18)
       at com.ryanheise.audioservice.AudioServicePlugin$BackgroundHandler.onPlay(AudioServicePlugin.java:494)
       at com.ryanheise.audioservice.AudioService$MediaSessionCallback$1.run(AudioService.java:536)
       at com.ryanheise.audioservice.AudioService$MediaSessionCallback.play(AudioService.java:552)
       at com.ryanheise.audioservice.AudioService$MediaSessionCallback.onPlay(AudioService.java:534)
       at android.support.v4.media.session.MediaSessionCompat$Callback$StubApi21.onPlay(MediaSessionCompat.java:1405)
       at android.support.v4.media.session.MediaSessionCompatApi21$CallbackProxy.onPlay(MediaSessionCompatApi21.java:196)
       at android.media.session.MediaSession$CallbackMessageHandler.handleMessage(MediaSession.java:1486)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6669)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by varun-gadre** [comment]
Can you post you post your flutter doctor --verbose
